FROM ruby:3.1.2

RUN apt-get update -qq \
    && apt-get install -y build-essential libpq-dev nodejs mariadb-client

# アプリ名
ENV APP_PATH /myapp
ENV BUNDLER_VERSION=2.3.11

RUN mkdir $APP_PATH
WORKDIR $APP_PATH

COPY Gemfile $APP_PATH/Gemfile
COPY Gemfile.lock $APP_PATH/Gemfile.lock
# Bundlerをアップデート これ書かないとrails newでエラー出た
RUN gem install bundler -v ${BUNDLER_VERSION} && \
    bundle install

COPY . $APP_PATH

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]